name: PHPUnit

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Composer install
      run: composer install --no-scripts --ignore-platform-reqs

    - name: Run tests
      run: vendor/bin/phpunit --coverage-clover=coverage.xml
      
    - name: Generate test coverage badge
      uses: timkrase/phpunit-coverage-badge@v1.2.0
      with:
        coverage_badge_path: 'badge-coverage.svg'
        push_badge: true
        repo_token: ${{ secrets.GITHUB_TOKEN }}
